
language: python
cache: pip

python:
  - '3.6'


install:
  - sudo pip install Django
  - sudo pip install chatterbot 

script:
- cd django_app
- timeout 20s python manage.py runserver 0:8080
  
        

notifications:
  slack:
    rooms:
      - finalcseproject:fm7EyjQgdk8HsSdLVXkKV0C4#project


