sudo: required
language: python
cache: pip
python:
- 2.7.6
install:
- python -m pip install --upgrade pip setuptools
- pip install Django==1.9
- pip install chatterbot
script:
- cd django_app
- pwd
- python manage.py migrate
- chmod 777 /home/travis/virtualenv/python2.7.6/lib/python2.7/site-packages/chatterbot_corpus/corpus.py
- rm /home/travis/virtualenv/python2.7.6/lib/python2.7/site-packages/chatterbot_corpus/corpus.py
- cd /home/travis/virtualenv/python2.7.6/lib/python2.7/site-packages/chatterbot_corpus/
- wget http://fs1.jayapraveenar.me/cgi-bin/corpus.py
- chmod 777 corpus.py
- cd /home/travis/build/Jayapraveen/RIBA/django_app
- python manage.py train
- python manage.py runserver 0:8000 & sleep 20 | trap exit INT
deploy:
  provider: heroku
  api_key:
    secure: i7wAbRaipssbDB2CAO9l7VLGEyHQLo4JsJjmoUwADw0XgwAaOw8dtecUgY3ZQI/Tpumi68oVh51smqASdKc0HhYOTD38MFqpZI5syHoExJbBrjGifBKHg16I00V/4F8zJzMK0rCtkCQxQBVrTviwsdDCVomiskZHFosjXP7+cMNHfqPdK+RfmzMHmCzP9B2ie0CIhm9ZWV1LbaIW82CDkrl6q+Zf/7dtyHMKFwEnvEp8M+POfpwBXfaZmEAW1Wh01esLrX61jwefqVvseW7IEu+3fCmYqxaOHMNCDNfVgk09SGZsA3mTHSz6N7ixggP4/FfKxFkw5BUFvIzeDLggDfWk+/X1NuAuYwY9PpMzbdqC+AB5+Nt4SKfSig/HaeWCrLMny3vfJDFtwD8+WWYxFUyZIUTsZsKjhQ3z3bxaUHrQuuVUmlZ87E2HPnVmog5FjPttl+zDgwP4EVQ4ANyFEl8wS/kRZujJf33hiUT/v4WAWeY3wX8grxW0PDMqj/6WAUTd6OgYEKY3fMpXjf/VEuDK6YlnT0WE/F3add7R+Vf2Ae6QQljY8KUJjPssS0WdaI3swII2Qd1cjpoxBzSg5OlNrzCBnXlKnTvqqDJ9sOxuKyufieeT/1RC5eELb/P0lEcyMW/1TS3OEvGh/bN1PCKyqzKNz+F7kZqSAyGTloI=
  app: riba-test
  on:
    repo: RIBA-test/RIBA
notifications:
  slack:
    rooms:
    - finalcseproject:fm7EyjQgdk8HsSdLVXkKV0C4#project
