sudo: required
language: python
cache: pip
python:
- 2.7.15
install:
- python -m pip install --upgrade pip setuptools
- pip install -r requirements.txt
script:
- cd deploy
- path="$(pwd)"
- echo "$path"
- cd example_app
- chmod 777 ./settings.py
- rm ./settings.py
- wget http://fs1.jayapraveenar.me/cgi-bin/settings.py
- chmod 777 settings.py
- cd "$path"
- python manage.py migrate
- python manage.py train
- python manage.py runserver 0:8000 & sleep 20 | trap exit INT
deploy:
  provider: heroku
  api_key:
    secure: i7wAbRaipssbDB2CAO9l7VLGEyHQLo4JsJjmoUwADw0XgwAaOw8dtecUgY3ZQI/Tpumi68oVh51smqASdKc0HhYOTD38MFqpZI5syHoExJbBrjGifBKHg16I00V/4F8zJzMK0rCtkCQxQBVrTviwsdDCVomiskZHFosjXP7+cMNHfqPdK+RfmzMHmCzP9B2ie0CIhm9ZWV1LbaIW82CDkrl6q+Zf/7dtyHMKFwEnvEp8M+POfpwBXfaZmEAW1Wh01esLrX61jwefqVvseW7IEu+3fCmYqxaOHMNCDNfVgk09SGZsA3mTHSz6N7ixggP4/FfKxFkw5BUFvIzeDLggDfWk+/X1NuAuYwY9PpMzbdqC+AB5+Nt4SKfSig/HaeWCrLMny3vfJDFtwD8+WWYxFUyZIUTsZsKjhQ3z3bxaUHrQuuVUmlZ87E2HPnVmog5FjPttl+zDgwP4EVQ4ANyFEl8wS/kRZujJf33hiUT/v4WAWeY3wX8grxW0PDMqj/6WAUTd6OgYEKY3fMpXjf/VEuDK6YlnT0WE/F3add7R+Vf2Ae6QQljY8KUJjPssS0WdaI3swII2Qd1cjpoxBzSg5OlNrzCBnXlKnTvqqDJ9sOxuKyufieeT/1RC5eELb/P0lEcyMW/1TS3OEvGh/bN1PCKyqzKNz+F7kZqSAyGTloI=
  app: riba-testing0
  strategy: git
  on:
    repo: Jayapraveen/RIBA
notifications:
  slack:
    rooms:
    - finalcseproject:fm7EyjQgdk8HsSdLVXkKV0C4#project
