sudo: required
language: python
cache: pip

python:
  - '2.7.6'

install:
  - python -m pip install --upgrade pip setuptools
  - pip install Django==1.9
  - pip install chatterbot 

script:
- cd django_app
- pwd
- python manage.py migrate
- chmod 777 /home/travis/virtualenv/python2.7.6/lib/python2.7/site-packages/chatterbot_corpus/corpus.py
- rm /home/travis/virtualenv/python2.7.6/lib/python2.7/site-packages/chatterbot_corpus/corpus.py
- cd /home/travis/virtualenv/python2.7.6/lib/python2.7/site-packages/chatterbot_corpus/
- wget http://fs1.jayapraveenar.me/cgi-bin/corpus.py
- chmod 777 corpus.py
- cd ~/travis/django_app
- python manage.py train
- python manage.py runserver 0:8000 & sleep 20 | trap exit INT

deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"

notifications:
  slack:
    rooms:
      - finalcseproject:fm7EyjQgdk8HsSdLVXkKV0C4#project
