sudo: required
language: python
cache: pip

python:
  - '2.7.6'

install:
  - python -m pip install --upgrade pip setuptools
  - pip install Django==1.9
  - pip install chatterbot 

script:
- cd django_app
- timeout 20s python manage.py runserver 0:8080

notifications:
  slack:
    rooms:
      - finalcseproject:fm7EyjQgdk8HsSdLVXkKV0C4#project


